### ISSUE TITLE
Error in Cache when used with Enum objects

### ISSUE THREAD

**Issue by manuel-hegner** [jtwig/jtwig#341] opened 2017-06-04 18:41 UTC
Hey, I found an error in the default configuration of JTWIG if you use enum objects as models. If the enum class defines an abstract method that is overridden by the enum values, the cache may return the java.lang.reflect.Method object belonging to another value than the current one and thus the invokation of the method will fail.

For example if my enum class Model has two values they have the classes Model$1 and Model$2. Using the cache the solver tries to execute invoke with the Model$2 instance on the calc method belonging to Model$1.

Without using the cache everything works as expected.

**Comment by lyncodev** [comment] 2017-06-13 23:04
@manuel-hegner thanks for pointing this out. This is a duplicate of #336. Fixed in the next release.

**Closed by lyncodev** 2017-06-13 23:04 UTC
Labels: Duplicate, ready
