### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by desanik** [jtwig/jtwig#314] opened 2016-06-20 09:54 UTC
Dont force users to to use slf4j please.
Solution:
http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by lyncodev** [comment] 2016-09-08 18:59
Hi @desanik, thanks for pointing out.
The issue has been fixed in jtwig-core v5.59

**Closed by lyncodev** 2016-09-08 18:59 UTC

**Comment by desanik** [comment] 2016-09-09 19:45
Wow! I never thought it would be fixed so fast. Thanks so much for saying thank you. I'd be nicer next time I find something. I hope I do, I mean, I hope I don't, you know what I mean...

**Comment by ben-manes** [comment] 2016-09-15 18:30
This should not be part of the library, nop is for applications. An application will now print the warning,

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ben/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.7/9865cf6994f9ff13fce0bf93f2054ef6c65bb462/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ben/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-nop/1.7.12/8052427115f80679a17bd2af659c760df39829bd/slf4j-nop-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

This requires then excluding nop, which is unfriendly.

**Comment by dkobia** [comment] 2017-02-10 14:51
Was fixed in v5.59, but slf4j is back in v5.70

**Comment by JacobAMason** [comment] 2017-06-14 06:48
Still here in 5.85.3.RELEASE
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by janoszen** [comment] 2017-06-14 06:53
@JacobAMason no, it is not. That is the intended behavior. Let me explain.

SLF4J uses a facade pattern to connect to multiple loggers. jTwig essentially sends log messages to the SLF4J facade, which then forwards them to whatever logger you are using. (e.g. log4j). However, if you have no logger set up, which is the case with your situation, there will be no logging done, hence the message.

To solve this, you will have to install some SLF4J logger binding. If you don't use any log system, simply use org.slf4j:slf4j-simple, which can be obtained from Maven Central.

I hope this helps.

**Comment by JacobAMason** [comment] 2017-06-27 02:13
Okay, that makes more sense. Thanks!
